[project]
name = "qwen"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mlx-lm>=0.26.2",
    "transformers>=4.54.1",
    "xmltodict>=0.14.2",
]
